"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };

var template = function template(files) {
  var fallback = arguments.length <= 1 || arguments[1] === undefined ? "/" : arguments[1];

  if (!Array.isArray(files)) {
    throw new Error("You must provide an array for " + "generating appcache template\n" + ("You are prodiving \"" + (typeof files === "undefined" ? "undefined" : _typeof(files)) + "\""));
  }

  return "CACHE MANIFEST\n# Appcache generated by Statinamic\n" + files.join("\n") + "\n\nNETWORK:\n*\n\nFALLBACK:\n" + fallback + " " + fallback;
};

exports.default = template;